/**
 * Actor resolution for system-initiated and chat-platform agent invocations.
 *
 * F-54 (scheduler) and F-55 (Slack/Teams/Discord) closed the same root cause:
 * the agent ran without a `user` bound to RequestContext, so
 * `checkApprovalRequired(undefined, ...)` short-circuited and the approval
 * gate silently disabled. These helpers produce an `AtlasUser` for those
 * surfaces so the gate fires correctly downstream.
 *
 * Two flavours:
 *
 * - `loadActorUser(userId, orgId)` — resolves a real Atlas user by id,
 *   primarily for the scheduler executor (the task row carries the
 *   `owner_id` that created it). Returns null when the row no longer exists
 *   so callers can fail-loud rather than impersonate a deleted account.
 *
 * - `botActorUser(...)` — synthesizes a chat-platform identity. Slack /
 *   Teams / Discord webhooks have no Atlas user in the inbound payload, so
 *   the agent runs under a stable synthetic id like `slack-bot:<teamId>`.
 *   Approval requests generated by these calls are tagged with this id, and
 *   the existing user-identity gate in `lib/tools/sql.ts` blocks the query
 *   with a clear "approve via the Atlas web app" message.
 */

import type { AtlasUser, AtlasRole } from "@atlas/api/lib/auth/types";
import { createAtlasUser } from "@atlas/api/lib/auth/types";
import { parseRole } from "@atlas/api/lib/auth/permissions";
import { hasInternalDB, internalQuery } from "@atlas/api/lib/db/internal";
import { createLogger } from "@atlas/api/lib/logger";
import { errorMessage } from "@atlas/api/lib/audit/error-scrub";

const log = createLogger("auth:actor");

const ROLE_LEVEL: Record<AtlasRole, number> = {
  member: 0,
  admin: 1,
  owner: 2,
  platform_admin: 3,
};

/**
 * Load a real Atlas user as an actor for a system-initiated call (e.g. the
 * scheduler executing a task on the user's behalf).
 *
 * Returns:
 *  - `null` when the user row is missing (deleted account / removed from
 *    org) or no internal DB is configured. Callers treat this as a
 *    permanent condition — pause / recreate the dependent resource.
 *  - **Throws** on transient DB errors (connection failure, timeout). The
 *    caller should mark the run as failed with the DB error message and
 *    let the next scheduler tick retry — distinguishing "permanent
 *    missing" from "transient DB blip" so operators don't get told to
 *    recreate tasks during a flapping internal database.
 *
 * Resolves the effective role by comparing the user-level role with the
 * org-level membership role and taking the higher of the two — same logic
 * as `validateManaged` so a scheduled task created by an org owner
 * (user.role="member", member.role="owner") still presents as owner.
 */
export async function loadActorUser(
  userId: string,
  orgId: string | null,
): Promise<AtlasUser | null> {
  if (!hasInternalDB()) return null;

  let userRows: { id: string; email: string | null; role: string | null }[];
  try {
    userRows = await internalQuery<{
      id: string;
      email: string | null;
      role: string | null;
    }>(
      `SELECT id, email, role FROM "user" WHERE id = $1 LIMIT 1`,
      [userId],
    );
  } catch (err) {
    log.error(
      { err: errorMessage(err), userId, orgId },
      "loadActorUser DB query failed — propagating so caller can distinguish from missing user",
    );
    throw err instanceof Error ? err : new Error(String(err));
  }

  if (userRows.length === 0) return null;

  const row = userRows[0];
  const userRole = parseRole(row.role ?? undefined);
  const effectiveRole = await resolveEffectiveRole(userRole, userId, orgId);

  return createAtlasUser(
    row.id,
    "managed",
    row.email || row.id,
    {
      ...(effectiveRole !== undefined ? { role: effectiveRole } : {}),
      ...(orgId !== null ? { activeOrganizationId: orgId } : {}),
      claims: orgId !== null ? { sub: row.id, org_id: orgId } : { sub: row.id },
    },
  );
}

async function resolveEffectiveRole(
  userRole: AtlasRole | undefined,
  userId: string,
  orgId: string | null,
): Promise<AtlasRole | undefined> {
  if (!orgId || !hasInternalDB()) return userRole;
  try {
    const rows = await internalQuery<{ role: string }>(
      `SELECT role FROM member WHERE "userId" = $1 AND "organizationId" = $2 LIMIT 1`,
      [userId, orgId],
    );
    if (rows.length === 0) return userRole;
    const orgRole = parseRole(rows[0].role);
    if (!orgRole) return userRole;
    const userLevel = ROLE_LEVEL[userRole ?? "member"] ?? 0;
    const orgLevel = ROLE_LEVEL[orgRole] ?? 0;
    return orgLevel > userLevel ? orgRole : (userRole ?? "member");
  } catch (err) {
    log.warn(
      { err: errorMessage(err), userId, orgId },
      "resolveEffectiveRole failed — falling back to user-level role",
    );
    return userRole;
  }
}

/**
 * Known chat-platform integrations. Const tuple + derived type matches the
 * codebase convention (`AUTH_MODES`, `APPROVAL_RULE_TYPES`, etc.) and
 * gives downstream code (audit emitters, claim validators, docs) a runtime
 * iterable list of valid platforms.
 */
export const CHAT_BOT_PLATFORMS = ["slack", "teams", "discord"] as const;
export type ChatBotPlatform = (typeof CHAT_BOT_PLATFORMS)[number];

/**
 * Build a synthetic actor for a chat-platform invocation. The resulting
 * `AtlasUser.id` is `${platform}-bot:${externalId}` (e.g. `slack-bot:T0123`)
 * so approval requests and audit rows from chat surfaces stay grouped and
 * recognizable. `mode: "simple-key"` reflects the absence of a Better Auth
 * session — the bot speaks for the workspace, not for any individual user.
 */
export function botActorUser(opts: {
  platform: ChatBotPlatform;
  externalId: string;
  orgId: string;
  externalUserId?: string;
}): AtlasUser {
  const idSuffix = opts.externalUserId
    ? `${opts.externalId}:${opts.externalUserId}`
    : opts.externalId;
  const id = `${opts.platform}-bot:${idSuffix}`;
  return createAtlasUser(id, "simple-key", id, {
    role: "member",
    activeOrganizationId: opts.orgId,
    claims: {
      sub: id,
      org_id: opts.orgId,
      chat_platform: opts.platform,
      external_id: opts.externalId,
      ...(opts.externalUserId !== undefined ? { external_user_id: opts.externalUserId } : {}),
    },
  });
}
