/**
 * `openapi-python-preamble` — generates the Python the sandbox seeds so the
 * agent can compose multi-step REST workflows in code (PRD #2868 "sandbox-
 * emitted Python", agent-execution-shape section).
 *
 * The generated preamble is a thin, dependency-free `AtlasRestClient` over the
 * Python stdlib (`urllib`) — NOT `httpx`. Stdlib keeps the client runnable in
 * any sandbox without a `pip install`, and keeps the acceptance suite's proof
 * harness hermetic. The operation table is baked from the slice-0
 * {@link OperationGraph} so the client dispatches by `operationId` exactly like
 * the TypeScript {@link executeOperation} primitive — no per-operation code.
 *
 * Execution status: slice 1 (#2924) GENERATED + unit-tested this preamble (it
 * compiles, and the acceptance suite runs it against a local mock to prove
 * "prompt -> Python -> API call -> answer"). Slice 3 (#2927) landed the network
 * boundary it depends on — the Vercel sandbox's egress is now narrowed
 * per-request to the datasource host (`tools/backends/network-allowlist.ts`) —
 * but this preamble is STILL not wired into the live `executePython` path. The
 * blocker is read-only: an in-sandbox HTTP client that can authenticate to the
 * upstream lets untrusted agent code issue *any* method (the per-host network
 * credential injection is method-agnostic, and Python introspection can reach
 * an exposed client's transport), which would break "read-only in this
 * release". Enabling it safely needs read-only enforced at a method-aware
 * host-side mediation point — deferred to a later slice (pairs with the slice-5
 * write-allowlist, #2929). Until then the live shape stays `executeRestOperation`
 * (single op) + sequential tool calls, where the credential and read-only guard
 * live server-side, never in the sandbox.
 *
 * Credentials are injected by env-var NAME (never inlined): a caller would seed
 * `process.env[authEnv]` / `process.env[baseUrlEnv]` into the sandbox
 * environment, and the generated code reads them at runtime. A token never
 * appears in the generated source. (Today only the hermetic acceptance harness
 * exercises this; the live path does not run the preamble.)
 */
import type { OperationGraph } from "./types";

export interface PreambleOptions {
  /** Env var name carrying the base URL, e.g. "ATLAS_REST_BASE_URL". */
  readonly baseUrlEnv: string;
  /** Env var name carrying the bearer token, e.g. "ATLAS_REST_TOKEN". */
  readonly authEnv: string;
  /** Per-request timeout in seconds. Defaults to 30 (matches the TS client). */
  readonly timeoutSeconds?: number;
}

/**
 * Generate the Python preamble that defines `atlas_rest` (an
 * {@link AtlasRestClient} instance) for the given operation graph.
 *
 * The agent's emitted body then calls e.g.:
 *   people = atlas_rest.call("findManyPeople", query={"filter": "emails.primaryEmail[eq]:a@b.com"})
 *   note = atlas_rest.call("findOneNote", path_params={"id": nid})
 */
export function buildRestClientPreamble(
  graph: OperationGraph,
  options: PreambleOptions,
): string {
  const timeout = options.timeoutSeconds ?? 30;
  const operationsLiteral = renderOperationsLiteral(graph);

  // NOTE: keep this as a plain template — no f-strings on the JS side beyond the
  // few interpolations below. The generated code must be valid Python 3.
  return `# AUTO-GENERATED by Atlas — generic REST client for "${pyComment(graph.info.title)}".
# Dispatches by operationId against the operation graph below. No per-operation
# code: add an operation to the upstream OpenAPI spec and it appears here.
import json, os, urllib.request, urllib.parse, urllib.error

ATLAS_REST_BASE_URL = os.environ[${pyStr(options.baseUrlEnv)}].rstrip("/")
ATLAS_REST_TOKEN = os.environ.get(${pyStr(options.authEnv)}, "")

# operationId -> {"method", "path"} (path may contain {tokens}).
OPERATIONS = ${operationsLiteral}


class AtlasRestError(Exception):
    def __init__(self, message, status):
        super().__init__(message)
        self.status = status


class AtlasRestClient:
    """Generic OpenAPI operation dispatcher (stdlib urllib, no third-party deps)."""

    def __init__(self, base_url=ATLAS_REST_BASE_URL, token=ATLAS_REST_TOKEN):
        self.base_url = base_url.rstrip("/")
        self.token = token

    def call(self, operation_id, path_params=None, query=None, body=None):
        op = OPERATIONS.get(operation_id)
        if op is None:
            raise AtlasRestError("Unknown operationId: %s" % operation_id, 0)

        path = op["path"]
        for key, value in (path_params or {}).items():
            path = path.replace("{%s}" % key, urllib.parse.quote(str(value), safe=""))

        url = self.base_url + path
        if query:
            pairs = [(k, v) for k, v in query.items() if v is not None]
            if pairs:
                url = url + "?" + urllib.parse.urlencode(pairs, doseq=True)

        headers = {"Accept": "application/json"}
        if self.token:
            headers["Authorization"] = "Bearer " + self.token

        data = None
        if body is not None and op["method"] not in ("GET", "HEAD"):
            data = json.dumps(body).encode("utf-8")
            headers["Content-Type"] = "application/json"

        req = urllib.request.Request(url, data=data, method=op["method"], headers=headers)
        try:
            with urllib.request.urlopen(req, timeout=${timeout}) as resp:
                raw = resp.read().decode("utf-8")
                return json.loads(raw) if raw else None
        except urllib.error.HTTPError as exc:
            detail = exc.read().decode("utf-8", "replace")
            raise AtlasRestError("HTTP %d: %s" % (exc.code, detail[:200]), exc.code)


atlas_rest = AtlasRestClient()
`;
}

/** Render the OPERATIONS dict as a sorted, valid Python literal. */
function renderOperationsLiteral(graph: OperationGraph): string {
  const entries = [...graph.operations.values()]
    .toSorted((a, b) => a.operationId.localeCompare(b.operationId))
    .map(
      (op) =>
        `    ${pyStr(op.operationId)}: {"method": ${pyStr(op.method)}, "path": ${pyStr(op.path)}},`,
    );
  return `{\n${entries.join("\n")}\n}`;
}

/** Python string literal with JSON-safe escaping (valid Python: JSON ⊂ Python). */
function pyStr(value: string): string {
  return JSON.stringify(value);
}

/** Sanitize a value for a single-line Python comment. */
function pyComment(value: string): string {
  return value.replace(/[\r\n]+/g, " ");
}
