/**
 * The Docusaurus OKF importer (#4392, PRD #4372) — the markdown-tree adapter
 * plus a sidebar filter keyed on Docusaurus's `sidebars.js`/`sidebars.ts`
 * config: only docs reachable from the sidebar collect; everything else under
 * the docs directory (retired pages, drafts, partials) is declined by the
 * `filter` hook and lands in the core's counted `skipped.filtered` bucket —
 * visible, never silent. The classic preset's docs tree is markdown-native;
 * the base adapter's fence-aware {@link stripMdxModuleLines} handles `.mdx`
 * module lines with no extra work here.
 *
 * A `sidebars.js`/`sidebars.ts` module must be EVALUATED (entries can be
 * computed at load time), which would force this package to either eval
 * arbitrary code or bundle a TS loader — both violate its fflate-only, no-eval
 * posture. So the evaluation seam is INJECTED, exactly like the markdown-tree
 * adapter's `parseYaml`: the caller (already in a JS runtime) does
 * `(await import(sidebarsPath)).default` (or `require`, or `JSON.parse` for a
 * `sidebars.json`) and hands over the plain object. This package owns the
 * RESOLVER — the sidebar walk, the `type: autogenerated` directory expansion,
 * and the fail-loud accounting — which is the actual logic and is fully
 * testable with plain objects.
 *
 * The sidebar walk resolves Docusaurus's item shapes structurally, exploiting
 * one invariant: a doc is named ONLY by a bare id string, a `type: doc`/`ref`
 * item's `id`, a `type: category` item's `link` (when that link is a `doc`),
 * or membership of a `type: autogenerated` directory. Category labels, `link`
 * items, `html` items, and `generated-index` category links never name a
 * source doc, so they contribute nothing.
 *
 * FAIL-LOUD ({@link NavManifestError}) on a non-object sidebars value or a
 * sidebar that resolves to zero docs — a broken sidebar must fail the build
 * where the site owner can act on it, never quietly produce an empty (or
 * over-full) bundle.
 */

import { NavManifestError } from "./errors";
import {
  createMarkdownTreeSource,
  DEFAULT_EXTENSIONS,
  type MarkdownTreeSourceOptions,
} from "./markdown-tree";
import type { DocSource, DocSourcePage } from "./types";

/** Default label used in {@link NavManifestError} messages — the sidebar is
 *  injected, so there is no file path to name unless the caller supplies one. */
export const DOCUSAURUS_SIDEBAR_LABEL = "sidebars";

/** The resolved navigation of one Docusaurus sidebar config. */
export interface DocusaurusSidebar {
  /** The label the resolution is reported under (default `sidebars`). */
  readonly label: string;
  /**
   * Sidebar-reachable doc ids, normalized to the tree adapter's path shape
   * minus the extension: `/`-separated, no leading slash, no `.md`/`.mdx`
   * (the filter strips `page.path`'s extension before membership).
   */
  readonly pages: ReadonlySet<string>;
}

export interface ResolveDocusaurusSidebarOptions {
  /** Page extensions the tree walk enumerates — kept in sync so doc-id and
   *  tree-path comparison strip the same set. Default `[".md", ".mdx"]`. */
  readonly extensions?: readonly string[];
  /** Label for {@link NavManifestError} messages. Default `sidebars`. */
  readonly label?: string;
}

export interface DocusaurusSourceOptions extends Omit<MarkdownTreeSourceOptions, "root"> {
  /** The Docusaurus DOCS directory — where the `.md`/`.mdx` files live and the
   *  sidebar's doc ids are relative to (classic preset default `docs/`). */
  readonly root: string;
  /**
   * The loaded sidebars config object (the default export of
   * `sidebars.js`/`sidebars.ts`, or the parsed `sidebars.json`). Injected so
   * this package never evaluates a JS/TS module itself. Either the sidebars
   * map (`{ docs: [...], api: [...] }`) or a single sidebar array.
   */
  readonly sidebars: unknown;
  /** Label for {@link NavManifestError} messages. Default `sidebars`. */
  readonly label?: string;
}

export interface DocusaurusSource {
  /** The underlying markdown-tree doc source (full docs tree; the sidebar does
   *  not narrow enumeration — filtering happens at collect so skips are
   *  counted). */
  readonly source: DocSource;
  /**
   * The sidebar predicate for the core collect's `filter` hook: `true` iff the
   * page is reachable from the sidebar. Pass to `collectPages`/`buildOkfBundle`.
   */
  readonly filter: (page: DocSourcePage) => boolean;
  /** The resolved sidebar — the reachable doc-id set. */
  readonly sidebar: DocusaurusSidebar;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/** Strip a trailing page extension (case-insensitive) so sidebar doc ids
 *  (extension-less by convention) and tree paths compare on the same stem. */
function stripPageExtension(path: string, extensions: readonly string[]): string {
  const lower = path.toLowerCase();
  for (const ext of extensions) {
    const suffix = ext.toLowerCase();
    if (lower.endsWith(suffix)) return path.slice(0, -suffix.length);
  }
  return path;
}

/** Normalize a doc id / dirName onto the tree adapter's path shape. Returns
 *  null for values that can never name a tree doc (external links, empties). */
function normalizeId(raw: string, extensions: readonly string[]): string | null {
  let path = raw.trim();
  if (path === "" || path.includes("://") || path.startsWith("//")) return null;
  while (path.startsWith("/")) path = path.slice(1);
  return stripPageExtension(path, extensions) || null;
}

/**
 * Resolve the doc id of an explicitly-typed `doc`/`ref` item (or a
 * `doc`-typed category link), FAIL-LOUD on a missing/non-string/unresolvable
 * `id`. Unlike a bare string (tolerated leniently, mirroring Mintlify's
 * non-`pages` skip), a typed item is UNAMBIGUOUSLY a doc reference — dropping
 * it silently would ship a partial bundle that never trips the zero-page guard
 * (an `id` computed to `undefined` in a JS sidebar is exactly this). So the
 * broken reference fails the build where the site owner can fix it.
 */
function requireDocId(
  rawId: unknown,
  itemType: string,
  extensions: readonly string[],
  label: string,
): string {
  if (typeof rawId !== "string") {
    throw new NavManifestError(
      label,
      `a "type: ${itemType}" sidebar item has a missing or non-string "id"`,
    );
  }
  const id = normalizeId(rawId, extensions);
  if (id === null) {
    throw new NavManifestError(
      label,
      `a "type: ${itemType}" sidebar item has an "id" ("${rawId}") that resolves to no doc path`,
    );
  }
  return id;
}

/**
 * Recursive walk of one sidebar node: collect explicit doc ids into `docIds`,
 * record `type: autogenerated` directories into `autogenDirs` for expansion
 * against the tree. Handles the top-level sidebars map, the legacy shorthand
 * category object (`{ "Label": [items] }`), and every item shape.
 */
function walkSidebar(
  node: unknown,
  extensions: readonly string[],
  label: string,
  docIds: Set<string>,
  autogenDirs: string[],
): void {
  if (typeof node === "string") {
    const id = normalizeId(node, extensions);
    if (id !== null) docIds.add(id);
    return;
  }
  if (Array.isArray(node)) {
    for (const element of node) walkSidebar(element, extensions, label, docIds, autogenDirs);
    return;
  }
  if (!isRecord(node)) return;

  if (typeof node.type === "string") {
    switch (node.type) {
      case "doc":
      case "ref": {
        docIds.add(requireDocId(node.id, node.type, extensions, label));
        return;
      }
      case "category": {
        // A category's landing page is a real doc only when the link is a
        // `doc` (a `generated-index` link has no source file). A `doc` link
        // with a broken `id` fails loud like any other typed doc reference.
        if (isRecord(node.link) && node.link.type === "doc") {
          docIds.add(requireDocId(node.link.id, "doc", extensions, label));
        }
        walkSidebar(node.items, extensions, label, docIds, autogenDirs);
        return;
      }
      case "autogenerated": {
        // Like a typed doc item, a `type: autogenerated` item is unambiguously
        // a doc-directory reference (Docusaurus requires `dirName`); a
        // missing/non-string dirName would silently omit every doc under it —
        // the same silent-partial class requireDocId guards. Fail loud. (An
        // empty-string dirName is meaningful: expandAutogenDir treats
        // `""`/`"."` as the whole tree.)
        if (typeof node.dirName !== "string") {
          throw new NavManifestError(
            label,
            'a "type: autogenerated" sidebar item has a missing or non-string "dirName"',
          );
        }
        autogenDirs.push(node.dirName);
        return;
      }
      // link / html / any other typed item names no source doc.
      default:
        return;
    }
  }

  // No `type`: the top-level sidebars map, or a shorthand category object —
  // keys are sidebar/category labels, values carry the docs. Recurse only into
  // array/object values: a bare-string value on a malformed no-type object is
  // a label, never a doc id (only the shapes above name docs).
  for (const value of Object.values(node)) {
    if (Array.isArray(value) || isRecord(value)) {
      walkSidebar(value, extensions, label, docIds, autogenDirs);
    }
  }
}

/** Expand one `type: autogenerated` dirName against the tree's normalized doc
 *  ids: every doc UNDER that directory. Order is moot — membership only, and
 *  the deterministic packer renders the bundle byte-stable regardless.
 *  `dirName: "."` / empty matches the whole tree. */
function expandAutogenDir(dirName: string, treeStems: readonly string[], out: Set<string>): void {
  let dir = dirName.trim().replaceAll("\\", "/");
  while (dir.startsWith("./")) dir = dir.slice(2);
  // Strip leading/trailing slashes with string ops, NOT a regex: a trailing-run
  // pattern like `/\/+$/` backtracks quadratically on a hostile many-slash
  // dirName (CodeQL js/polynomial-redos — dirName is library-supplied), and
  // this package's posture is string ops for exactly that (see markdown-tree.ts).
  let start = 0;
  while (start < dir.length && dir.charAt(start) === "/") start++;
  let end = dir.length;
  while (end > start && dir.charAt(end - 1) === "/") end--;
  dir = dir.slice(start, end);
  for (const stem of treeStems) {
    if (dir === "" || dir === "." || stem.startsWith(`${dir}/`)) out.add(stem);
  }
}

/**
 * Resolve a loaded Docusaurus sidebars config to the set of reachable doc
 * ids, expanding `type: autogenerated` categories against the docs tree.
 * `treePaths` are the tree adapter's page paths (with extensions).
 *
 * Fail-loud ({@link NavManifestError}) on a sidebars value that is neither the
 * sidebars map nor a sidebar array, or a sidebar that resolves to zero docs
 * (every tree page would be filtered out — a broken sidebar, never a silent
 * empty bundle).
 */
export function resolveDocusaurusSidebar(
  sidebars: unknown,
  treePaths: readonly string[],
  options: ResolveDocusaurusSidebarOptions = {},
): DocusaurusSidebar {
  const extensions = options.extensions ?? DEFAULT_EXTENSIONS;
  const label = options.label ?? DOCUSAURUS_SIDEBAR_LABEL;
  if (!isRecord(sidebars) && !Array.isArray(sidebars)) {
    throw new NavManifestError(
      label,
      "the sidebars config is not an object — expected the sidebars map or a sidebar array",
    );
  }

  const docIds = new Set<string>();
  const autogenDirs: string[] = [];
  walkSidebar(sidebars, extensions, label, docIds, autogenDirs);

  if (autogenDirs.length > 0) {
    const treeStems = treePaths.map((p) => stripPageExtension(p.replaceAll("\\", "/"), extensions));
    for (const dir of autogenDirs) expandAutogenDir(dir, treeStems, docIds);
  }

  if (docIds.size === 0) {
    throw new NavManifestError(
      label,
      "the sidebar resolves to no page paths — every tree page would be filtered out",
    );
  }
  return { label, pages: docIds };
}

/**
 * Build a Docusaurus doc source: {@link createMarkdownTreeSource} over the
 * docs directory plus the sidebar `filter` derived from the loaded sidebars
 * config. Usage:
 *
 * ```ts
 * const sidebars = (await import(sidebarsPath)).default;
 * const { source, filter } = await createDocusaurusSource({ root, parseYaml, sidebars });
 * const result = await buildOkfBundle(source, { prefix: "docs", filter });
 * // result.stats.skipped.filtered — docs on disk but absent from the sidebar
 * ```
 */
export async function createDocusaurusSource(
  options: DocusaurusSourceOptions,
): Promise<DocusaurusSource> {
  const { sidebars, label, ...treeOptions } = options;
  const extensions = options.extensions ?? DEFAULT_EXTENSIONS;
  const source = await createMarkdownTreeSource(treeOptions);
  const treePaths = source.getPages().map((page) => page.path);
  const sidebar = resolveDocusaurusSidebar(sidebars, treePaths, { extensions, label });
  const reachable = sidebar.pages;
  return {
    source,
    filter: (page) => reachable.has(stripPageExtension(page.path, extensions)),
    sidebar,
  };
}
