import type { Metadata } from "next";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { buildThemeInitScript } from "@/ui/hooks/theme-init-script";
import { AuthGuard } from "@/ui/components/auth-guard";
import { QueryProvider } from "@/ui/components/query-provider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Atlas",
  description: "Ask your data anything",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Inline script to set dark class before first paint — prevents flash.
            Reads atlas-theme from localStorage: "dark" → always dark, "light" → always light,
            "system" or missing → follows prefers-color-scheme.
            Generated by buildThemeInitScript() to stay in sync with use-dark-mode.ts. */}
        <script dangerouslySetInnerHTML={{ __html: buildThemeInitScript() }} />
      </head>
      <body className="bg-white text-zinc-900 antialiased dark:bg-zinc-950 dark:text-zinc-100">
        <a href="#main" className="sr-only focus:not-sr-only focus:absolute focus:z-50 focus:p-4 focus:bg-background focus:text-foreground">Skip to content</a>
        <QueryProvider><NuqsAdapter><AuthGuard>{children}</AuthGuard></NuqsAdapter></QueryProvider>
      </body>
    </html>
  );
}
